### ISSUE TITLE
Django 1.9: ImportError: cannot import name SingleRelatedObjectDescriptor 

### ISSUE THREAD

**Issue by matias-hhh** [chrisglass/django_polymorphic#184] opened 2015-12-21 22:13 UTC
I'm using version 0.7.2 (as dependency for django-filer) with Django 1.9, and have been getting this error randomly from time to time, and when i refresh page it just goes away.

The exception happens in polymorphic_model.py in \_\_init\_\_, line 176, where it tries to import the SingleRelatedObjectDescriptor

I think the issue is because of the Django 1.9 api change, from the release notes:

The related model object descriptor classes in django.db.models.fields.related (private API) are moved from the related module to related_descriptors and renamed as follows:

- ReverseSingleRelatedObjectDescriptor is ForwardManyToOneDescriptor
- SingleRelatedObjectDescriptor is ReverseOneToOneDescriptor
- ForeignRelatedObjectsDescriptor is ReverseManyToOneDescriptor
- ManyRelatedObjectsDescriptor is ManyToManyDescriptor

**Comment by eriktelepovsky** [comment] 2015-12-22 03:18
Duplicate of #165

**Closed** 2015-12-22 10:12 UTC
